use std::error;

fn main() -> Result<(), Box<dyn error::Error>> {
    println!("hey yo!");
    Ok(())
}
